// <auto-generated />
using System;
using MITCRMS.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MITCRMS.Migrations
{
    [DbContext(typeof(MitcrmsContext))]
    partial class MitcrmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MITCRMS.Models.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8f2e7bb-9f34-4b97-8b7c-1a5e46c77e42"),
                            DateCreated = new DateTime(2026, 3, 10, 9, 3, 55, 472, DateTimeKind.Utc).AddTicks(903),
                            DepartmentCode = "D.O.S-001",
                            DepartmentName = "Director of Studies"
                        });
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ApprovedByAdminId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2719e67-52f4-4f9c-bdb2-123456789abc"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("a45c9e02-1f0b-4e57-b3d8-9b77b4a302be"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Hod"
                        },
                        new
                        {
                            Id = new Guid("6e3d4978-dcb0-42ea-9c48-7f6209d4a871"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Bursar"
                        },
                        new
                        {
                            Id = new Guid("6e3d4978-dcb0-42ea-9c48-7f6209d4a882"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("6e3d4978-dcb0-42ea-9c48-7f6209d4a856"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Tutor"
                        });
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8f2e5ab-9f34-4b97-8b7c-1a5e86c77e42"),
                            Address = "Ogun State",
                            DateCreated = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("c8f2e7bb-9f34-4b97-8b7c-1a5e46c77e42"),
                            Email = "Admin001@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "SuperAdmin",
                            LastName = "Mitcrms",
                            PasswordHash = "AQAAAAIAAYagAAAAEJjieFsJGM2Xgr+WpuS3juOABbBCvbqSvpym4WzP/SDMuvGz6qH+EFgm19l8SUHUGA==",
                            PhoneNumber = "+23470456780"
                        });
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ad9b1e1-4c23-46a2-b8e4-219ab417f71f"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = new Guid("d2719e67-52f4-4f9c-bdb2-123456789abc"),
                            UserId = new Guid("c8f2e5ab-9f34-4b97-8b7c-1a5e86c77e42")
                        });
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Report", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.User", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.UserRole", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MITCRMS.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.User", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
